# 22-07-05 data analysis 실습

# 실습 1

In [1]:
import numpy as np

In [2]:
a = np.ones((3,3,3))
a[0] = np.arange(0,9).reshape(3,3)
a[1] = np.arange(9,0,-1).reshape(3,3)
a[2][0] = np.arange(-7,-10,-1)
a[2][1] = np.arange(-4,-7,-1)
a[2][2] = np.arange(-1,-4,-1)
print(a)

[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9.  8.  7.]
  [ 6.  5.  4.]
  [ 3.  2.  1.]]

 [[-7. -8. -9.]
  [-4. -5. -6.]
  [-1. -2. -3.]]]


In [3]:
a[1] = -1
print(a)

[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[-1. -1. -1.]
  [-1. -1. -1.]
  [-1. -1. -1.]]

 [[-7. -8. -9.]
  [-4. -5. -6.]
  [-1. -2. -3.]]]


In [5]:
import random
name_arr = np.array(['지빈', '명환', '연지', '하람', '연지', '진호', '월하', '연지' ])
data_arr = np.random.randn(8,4)

['지빈' '명환' '연지' '하람' '연지' '진호' '월하' '연지']
[[-2.2101516  -0.46759891 -1.14292574 -0.16673479]
 [-0.66502786  0.31903852  0.60258278  1.06550165]
 [-1.15734713 -0.52242562  0.13966309  1.40458495]
 [ 0.66667846 -0.63809464  0.77806716 -1.1494361 ]
 [-1.27989638  0.25651002 -0.15559312 -0.22281766]
 [ 0.29042278 -2.03880807  0.21347294  0.31241339]
 [-1.94019123  0.68588128 -2.36065662 -0.61325743]
 [-0.21030745 -0.41795583  0.73171776 -0.69709506]]


In [6]:
print(name_arr == '연지')

[False False  True False  True False False  True]


In [7]:
print(data_arr[name_arr == '연지'])

[[-1.15734713 -0.52242562  0.13966309  1.40458495]
 [-1.27989638  0.25651002 -0.15559312 -0.22281766]
 [-0.21030745 -0.41795583  0.73171776 -0.69709506]]


In [8]:
print(data_arr[name_arr == '연지', 2:]) # 그행의 열이 2번째부터 끝까지

[[ 0.13966309  1.40458495]
 [-0.15559312 -0.22281766]
 [ 0.73171776 -0.69709506]]
